linuxdeepin/dtkdeclarative

archlinux/PKGBUILD
=> feat: support build package for archlinux

README.md, README_zh_CN.md
Add todo lists.
Add the other languages link for README.md.
Log:
=> chore: Update README

CMakeLists.txt, debian/rules, docs/CMakeLists.txt
追加基于 doxygen 的文档构建
Related: https://github.com/linuxdeepin/dtkcore/pull/71 https://github.com/linuxdeepin/dtkwidget/pull/121
=> chore: build doxygen documentation

src/private/dblurimagenode.cpp
Because InWindowBlur's hardware rendering is bound with a custom FBO,
the FBO of Qt cannot be used in `grabToImage`, resulting in afterimage.
When binding the custom FBO, record the FBO of Qt. After the blur is
completed, reset the FBO of Qt.
Log:
Change-Id: If5799a139c4bc098fd126f8615eb24612c8e24c9
=> fix: InWindowBlur appears afterimage when call grabToImage

README.md, README_zh_CN.md
Change README to satisfy the open-source rules. Add more details to
English version. Modify the content of Chinese version.
Log: Change README to satisfy the open-source rules
=> chore: Change README

src/qml/DialogTitleBar.qml, src/qml/FlowStyle.qml, src/qml/TitleBar.qml
set titlebar layout leftmargin 10
Bug: https://pms.uniontech.com/bug-view-168245.html
Change-Id: Id79629c1ec6d5378eb1522f5602433a640832027
=> fix: titlebar left margin not set

src/qml/FlowStyle.qml
hovered / pressed color tweak
Bug: https://pms.uniontech.com/bug-view-168253.html
Change-Id: Idc7dcc383f223c2e93110312ca62bdd44f28c746
=> fix: hovered / pressed color not right

.reuse/dep5, debian/control
translation depends qttools5-dev-tools package.
Log: 翻译依赖qttools5-dev-tools包
Influence: 打包错误
Change-Id: I3ed7885898e8ded9cbcd9ce203c057697c375c24
=> fix: translation depends qttools5-dev-tools

examples/exhibition/Dialog.qml, src/qml/FlowStyle.qml
Adapt RecommendButton's style.
Log: 按照设计调整按钮颜色
Bug: https://pms.uniontech.com/bug-view-168405.html Influence: RecommendButton样式
Change-Id: I42da2c84533bbd8b5c5edcc1fbcca0e08c515447
=> fix: Adjust RecommendButton's style

src/qml/DialogWindow.qml
handler error.
Log: 窗口关闭错误
Change-Id: I0aa6c2433298b0649b1a85672b07594aa5113c8a
=> fix: Window close error

.reuse/dep5, .tx/deepin.conf, debian/changelog
update changelog
Log: update changelog
Change-Id: I5418f881366bcd987c407fa947f4a822e67058af
=> chore: update changelog

docs/qml/RectangularShadow.zh_CN.dox, docs/qml/SearchEdit.zh_CN.dox, docs/qml/Slider.zh_CN.dox, docs/qml/SpinBox.zh_CN.dox
=> docs: update docs

docs/qml/ControlBackground.zh_CN.dox, docs/qml/Ipv4Edit.zh_CN.dox, docs/qml/ItemDelegate.zh_CN.dox, docs/qml/StyledBehindWindowBlur.zh_CN.dox, docs/qml/Switch.zh_CN.dox, docs/qml/TextField.zh_CN.dox, src/qml/ControlBackground.qml, src/qml/RoundButton.qml
=> docs: update qml docs and add todo tags

README.md, README.zh_CN.md
=> docs: update README.md

README.md, README.zh_CN.md
去除 README.md 中的错误链接（不可见*导致404）
Log:
=> docs: fix error link

src/CMakeLists.txt, tests/main.cpp
ut error because appid is inconsistent.
Log: none
Change-Id: Ib532d2e91c1827deaa5fdbee10033cea45f0f2ec
=> chore: ut error and support list qml for qtcreator

src/qml/FlowStyle.qml
Add implementation about RecommandButton's palette.
Log: none
Change-Id: Ibd473422df51a262550d3b051d6a1230152ef279
=> fix: RecommandButton's color error when switch to dark theme

examples/qml-inspect/Example_TitleBar.qml, examples/qml-inspect/main.cpp, src/qml/AboutDialog.qml, src/qml/FlowStyle.qml, src/translations/dtkdeclarative.ts, src/translations/dtkdeclarative_az.ts, src/translations/dtkdeclarative_bo.ts, src/translations/dtkdeclarative_ca.ts, src/translations/dtkdeclarative_de.ts, src/translations/dtkdeclarative_es.ts, src/translations/dtkdeclarative_fi.ts, src/translations/dtkdeclarative_hu.ts, src/translations/dtkdeclarative_nl.ts, src/translations/dtkdeclarative_pl.ts, src/translations/dtkdeclarative_sq.ts, src/translations/dtkdeclarative_ug.ts, src/translations/dtkdeclarative_uk.ts, src/translations/dtkdeclarative_zh_CN.ts, src/translations/dtkdeclarative_zh_HK.ts, src/translations/dtkdeclarative_zh_TW.ts
Change layout From Vertical to Horizontal
Log: none
Issue: https://github.com/linuxdeepin/dtkdeclarative/issues/84
Change-Id: If91c8c3bd3c7ce2fb49edd2c88a8021ca5fdf6a9
=> feat: Modify AboutDialog's style

CMakeLists.txt, chameleon/CMakeLists.txt, qmlplugin/CMakeLists.txt
Log: use -DQML_INSTALL_DIR=path/to/install
=> feat: allow custom QML plugin install path

src/dapploader.cpp
=> fix: build failure on aarch64

CMakeLists.txt, debian/changelog
=> chore: update changelog to 5.6.8

docs/DevSpecification.zh_CN.md
Standardize title level of DevSpecifications.md to fix qch generate error.
Log: fix qch generate error
=> fix: qch generate error

CMakeLists.txt, qmlplugin/qmlplugin_plugin.cpp, src/private/dquickcontrolpalette.cpp, src/private/dquickcontrolpalette_p.h, src/qml/BoxPanel.qml, tests/CMakeLists.txt, tests/data.qrc, tests/main.cpp, tests/qml/ColorSelector_GetColorFromProperty.qml, tests/ut_colorselector.cpp
=> Fix ColorSelector.xxx properties maybe is undefined

examples/exhibition/main.cpp, examples/exhibition/main.qml
=> feat: display the scene graph backend name on dtk-exhibition

src/qml/FlowStyle.qml
According to the design drawing.
Issue: https://github.com/linuxdeepin/dtk/issues/47
=> fix: Modify IconButton's size for Combobox

debian/changelog, debian/control
=> chore: bump version to 5.6.12

CMakeLists.txt, chameleon/CMakeLists.txt, debian/rules, docs/CMakeLists.txt, examples/exhibition/CMakeLists.txt, examples/qml-inspect/CMakeLists.txt, linglong.yaml, qmlplugin/CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
Add DTK_VERSION to control dtk's version
=> feat: Support switching qt5 and qt6 for cmake

qmlplugin/qmlplugin_plugin.cpp
Ensure DGuiApplicationHelper is main thread.
=> fix: Crashed while debugging in Qt

chameleon/src/qtquickcontrols2chameleonstyleplugin.h, examples/exhibition/main.cpp, examples/qml-inspect/main.cpp, qmlplugin/qmlplugin_plugin.cpp, src/dapploader.cpp, src/dquickitemviewport.cpp, src/dquickitemviewport.h, src/dquickwindow.cpp, src/private/dblitframebuffernode.cpp, src/private/dblurimagenode.cpp, src/private/dblurimagenode_p.h, src/private/dconfigwrapper.cpp, src/private/dhandlecontextmenuwindow.cpp, src/private/dmaskeffectnode.cpp, src/private/dmaskeffectnode_p.h, src/private/dpopupwindowhandle.cpp, src/private/dqmlglobalobject.cpp, src/private/dquickcontrolpalette.cpp, src/private/dquickiconlabel.cpp, src/private/dquickiconlabel_p.h, src/private/dquickimageprovider.cpp, src/private/drectanglenode.cpp, src/private/drectanglenode_p.h, src/private/dshadownode_p.cpp, src/private/dshadownode_p.h
TODO: Support Render using OpenGL in Qt6
=> feat: Support compiling between Qt5 and Qt6

src/private/dhandlecontextmenuwindow.cpp
Adapt changes of QtPrivate's API.
=> feat: Forward ContentMenuEvent in Qt6

examples/qml-inspect/Example_colorselector.qml, src/qml/FlowStyle.qml
it introduces in e00402256828d742054d946b369aadfed39da6a6
`()` is compitable with qt6.
=> fix: Qt.color is invalid in qt5

examples/qml-inspect/Example_1.qml
=> fix: Syntax error in qt6

src/CMakeLists.txt, src/dtkdeclarative_assets.qrc, src/private/dmaskeffectnode.cpp, src/private/drectanglenode.cpp, src/private/drectanglenode_p.h, src/private/dshadownode_p.cpp, src/shaders_ng/cornerscolorshader.frag, src/shaders_ng/cornerscolorshader.vert, src/shaders_ng/quickitemviewport-opaque.frag, src/shaders_ng/quickitemviewport-opaque.vert, src/shaders_ng/quickitemviewport.frag, src/shaders_ng/quickitemviewport.vert, src/shaders_ng/shadowmaterial.frag, src/shaders_ng/shadowmaterial.vert
Adapt to changes in QSGMaterialShader and add shaders_ng.
=> feat: Forward shaders in qt6

qmlplugin/qmlplugin_plugin.cpp, qt6/src/dquickextendregister_p.h, src/dquickblitframebuffer.h, src/dquickitemviewport.h, src/dquickwindow.h, src/private/dconfigwrapper_p.h, src/private/dhandlecontextmenuwindow_p.h, src/private/dmessagemanager_p.h, src/private/dobjectmodelproxy_p.h, src/private/dpopupwindowhandle_p.h, src/private/dqmlglobalobject_p.h, src/private/dquickapploaderitem_p.h, src/private/dquickarrowboxpath_p.h, src/private/dquickbehindwindowblur_p.h, src/private/dquickcoloroverlay_p.h, src/private/dquickcontrolpalette_p.h, src/private/dquickdciicon_p.h, src/private/dquickdciiconimage_p.h, src/private/dquickglow_p.h, src/private/dquickiconimage_p.h, src/private/dquickiconlabel_p.h, src/private/dquickinwindowblur_p.h, src/private/dquickkeylistener_p.h, src/private/dquickopacitymask_p.h, src/private/dquickrectangle_p.h, src/private/dquickwaterprogressattribute_p.h, src/private/dsettingscontainer_p.h
=> feat: Add macro registing to Qt Meta system

.gitignore
Add new rules to .gitignore
Log: 添加文件忽略规则，防止编译产生的文档主题文件污染git目录
Issue: https://github.com/linuxdeepin/dtk/issues/99
=> chore: ignore doxygen-theme folder

cmake/DtkBuildConfig.cmake, qt6/src/CMakeLists.txt, src/CMakeLists.txt
=> fix: Missing dtkdeclarative_config.h in dev package

tests/CMakeLists.txt, tests/test_helper.hpp, tests/ut_dapploader.cpp
=> feat: Add unit-test for DAppLoader

qt6/src/CMakeLists.txt, src/CMakeLists.txt
=> chore: put gen header to CMAKE_CURRENT_BINARY_DIR

examples/exhibition/main.cpp, examples/qml-inspect/main.cpp
example should use plugin in source
=> fix: examples not use qml plugin in source

qt6/src/qml/WindowButtonGroup.qml, src/qml/WindowButtonGroup.qml, tests/CMakeLists.txt, tests/data.qrc, tests/main.cpp, tests/qml/ColorSelector_GetColorFromProperty.qml, tests/qml/CustomThemeMenu.qml, tests/qml/WindowButtonGroup.qml, tests/test_helper.hpp, tests/ut_colorselector.cpp, tests/ut_thememenu.cpp, tests/ut_windowbuttongroup.cpp
Add unit-test for ThemeMenu.
Add unit-test for WindowButtonGroup.
=> feat: Add unit-test for qml

tests/CMakeLists.txt, tests/data.qrc, tests/qml/DQuickRectangle.qml, tests/test_helper.hpp, tests/ut_dquickrectangle.cpp
Add ut.
Add QuickViewHelper for UT which need to show.
=> feat: Add ut for DQuickRectangle

src/dquickwindow.cpp, tests/CMakeLists.txt, tests/data.qrc, tests/qml/DQuickWindow.qml, tests/qml/QmlGlobalObject.qml, tests/ut_dqmlglobalobject.cpp, tests/ut_dquickwindow.cpp
Add DQuickWindow unit-test and DColor
=> feat: Add ut for DQuickWindow and DColor

tests/ut_waterprogressbar.cpp
Using ScopedPointer to Manage `water`.
=> fix: UT memory leak

tests/test_helper.hpp, tests/ut_colorselector.cpp, tests/ut_dqmlglobalobject.cpp, tests/ut_dquickrectangle.cpp, tests/ut_dquickwindow.cpp, tests/ut_thememenu.cpp, tests/ut_waterprogressbar.cpp, tests/ut_windowbuttongroup.cpp
=> typo: typo error

tests/CMakeLists.txt, tests/data.qrc, tests/qml/KeySequenceEdit.qml, tests/test_helper.hpp, tests/ut_keysequencelistener.cpp
=> feat: Add UT for KeySequence

src/private/dsettingscontainer_p.h, tests/CMakeLists.txt, tests/data.qrc, tests/qml/SettingsContainer.qml, tests/qml/SettingsContainer_View.qml, tests/test_helper.hpp, tests/ut_dsettingscontainer.cpp
=> feat: Add UT for SettingsContainer

tests/CMakeLists.txt, tests/data.qrc, tests/qml/ObjectModelProxy.qml, tests/ut_dobjectmodelproxy.cpp
=> feat: Add UT for ObjectModelProxy

tests/CMakeLists.txt, tests/data.qrc, tests/qml/MessageManager.qml, tests/ut_dmessagemanager.cpp
=> feat: Add UT for MessageManager

qt6/src/qml/AboutAction.qml, src/qml/AboutAction.qml
=> fix: Access null object for Action's object

tests/CMakeLists.txt, tests/data.qrc, tests/qml/ArrowBoxPath.qml, tests/ut_dquickarrowboxpath.cpp
=> feat: add UT for ArrowBoxPath

tests/CMakeLists.txt, tests/data.qrc, tests/main.cpp, tests/qml/GlowEffect.qml, tests/ut_dquickglow.cpp
add unit test ut_dquickglow
Log: add unit test ut_dquickglow
=> chore: add unit test ut_dquickglow

src/private/dsoftwareroundedimagenode.cpp, tests/CMakeLists.txt, tests/data.qrc, tests/qml/DSoftwareRoundedImageNodeItem.qml, tests/test_helper.hpp, tests/ut_dsoftwareroundedimagenode.cpp
=> feat: Add UT for DSoftwareRoundedImageNode

tests/CMakeLists.txt, tests/data.qrc, tests/qml/DBlitFramebufferNodeItem.qml, tests/test_helper.hpp, tests/ut_dblitframebuffernode.cpp
=> feat: Add UT for DBlitFramebufferNode

tests/CMakeLists.txt, tests/data.qrc, tests/qml/IconLabel.qml, tests/ut_dquickiconlabel.cpp
unit test
Log: add unit test ut-iconlabel
=> chore: add unit test ut-iconlabel

tests/CMakeLists.txt, tests/data.qrc, tests/icon/red.svg, tests/qml/QtIcon.qml, tests/ut_dquickiconimage.cpp
add unit test
Log: add unit test ut-iconimage
=> chore: add unit test ut-iconimage

tests/CMakeLists.txt, tests/data.qrc, tests/qml/DciIcon.qml, tests/ut_dquickdciiconimage.cpp
unit test
Log: add unit test ut-dciiconimage
=> chore: add unit test ut-dciiconimage

tests/CMakeLists.txt, tests/data.qrc, tests/qml/DMaskEffectNode.qml, tests/qml/DMaskEffectNode_TextureMaterial.qml, tests/test_helper.hpp, tests/ut_dmaskeffectnode.cpp
=> feat: Add UT for MaskEffectNode

tests/CMakeLists.txt, tests/ut_dquickdciicon.cpp
unit test
Log: add unit test ut_dquickdciicon
=> chore: add unit test ut_dquickdciicon

qt6/src/CMakeLists.txt, src/CMakeLists.txt, src/targets.cmake
=> fix: Compiling error for missing dependency

tests/CMakeLists.txt, tests/data.qrc, tests/qml/ContextMenuWindow.qml, tests/test_helper.hpp, tests/ut_dhandlecontextmenuwindow.cpp
add unit test
Log: add unit test ut-contextMenuWindow
=> chore: add unit test ut-contextMenuWindow

tests/CMakeLists.txt, tests/data.qrc, tests/qml/DQuickBehindWindowBlur.qml, tests/ut_dquickbehindwindowblur.cpp
=> feat: Add UT for BehindWindowBlur

tests/CMakeLists.txt, tests/data.qrc, tests/qml/DQuickInWindowBlur.qml, tests/test_helper.hpp, tests/ut_dquickinwindowblur.cpp
=> feat: Add UT for DQuickInWindowBlur

tests/CMakeLists.txt, tests/data.qrc, tests/qml/SoftwareColorOverlay.qml, tests/ut_dquickcoloroverlay.cpp
add unit test
Log: add unit test ut-dquickcoloroverlay
=> chore: Add unit test ut-dquickcoloroverlay

tests/CMakeLists.txt, tests/data.qrc, tests/qml/DQuickItemViewport.qml, tests/qml/DQuickItemViewport_HideSource.qml, tests/test_helper.hpp, tests/ut_dquickitemviewport.cpp
=> feat: Add UT for DQuickItemViewport

tests/CMakeLists.txt, tests/data.qrc, tests/qml/SoftwareOpacityMask.qml, tests/ut_dquickopacitymask.cpp
add unit test
Log: add unit test ut_dquickopacitymask
=> chore: Add unit test ut_dquickopacitymask

tests/data.qrc, tests/qml/QmlGlobalObject_MessageManager.qml, tests/ut_dqmlglobalobject.cpp
unit test
Log: Complementary unit test ut-globalobject
=> chore: Complementary unit test ut-globalobject

tests/ut_dqmlglobalobject.cpp
=> fix: UT failed when unreset palette

tests/CMakeLists.txt, tests/data.qrc, tests/qml/DQuickBlitFramebuffer.qml, tests/ut_dquickblitframebuffer.cpp
=> feat: Add UT for DQuickBlitFrameBuffer

qt6/src/qml/FlowStyle.qml, qt6/src/qml/PageIndicator.qml, src/qml/FlowStyle.qml, src/qml/PageIndicator.qml
it introduced in 8d2a959714408441ccd1e0ddfe07d2165f324021
=> fix: PageIndicator is invalid

tests/data.qrc, tests/qml/Config.qml, tests/ut_dconfigwrapper.cpp
unit test
Log: Complementary unit test ut-dconfigwrapper
=> chore: Complementary unit test ut-dconfigwrapper

misc/qml-app-template/CMakeLists.txt, misc/qml-app-template/src/main/CMakeLists.txt, misc/qml-app-template/src/maincomponentplugin/CMakeLists.txt, misc/qml-app-template/src/preloadplugin/CMakeLists.txt, misc/qml-app-template/wizard.json
=> feat: Adapt to switch qt6 and qtf for qml-app-template

src/private/dconfigwrapper.cpp, tests/data/dconf-example.meta.json, tests/qml/Config.qml, tests/ut_dconfigwrapper.cpp
Add ut-test for undefined property.
Fix some error for DConfigWrapper.
=> fix:  Wrong DConfigWrapper's property value and signal

src/private/dblitframebuffernode.cpp, src/private/dblurimagenode.cpp, src/private/dquickcontrolpalette.cpp, src/private/dquickcontrolpalette_p.h
=> feat: Adapt to qt6.4.2

archlinux/PKGBUILD
=> fix: PKGBUILD qml_install_dir needs to be overrided

qt6/src/qml/DialogButtonBox.qml, src/qml/DialogButtonBox.qml
Get implicitHeight from  DS.Style.button.height
=> fix: Wrong height of DialogButtonBox

examples/exhibition/main.cpp, examples/qml-inspect/main.cpp, src/private/dpopupwindowhandle.cpp
The function is removed Temporarily.
Issue: https://github.com/linuxdeepin/dtk/issues/98
Issue: https://github.com/linuxdeepin/dtk/issues/70
=> fix: Wrong style for PopupWindow

docs/DevSpecification.zh_CN.md, docs/qml/noqml/dquicksettingcontainer.zh_CN.dox, docs/qml/settings/SettingDialog.zh_CN.dox, examples/qml-inspect/Example_settingsdialog.qml
=> chore: correct typos in docs of Settings.ComboBox

debian/dtk-exhibition.install, examples/exhibition/CMakeLists.txt, examples/exhibition/dtk-exhibition.desktop.in
- chore: remove dtk-exhibition's desktop in debian
- chore: remove dtk-exhibition's dekstop in cmake
=> exhibition desktop

CMakeLists.txt
Fix:  Unknown CMake command "_qt_internal_suggest_dependency_debugging"
=> fix: find Qt Core before QuickControls2

.github/workflows/call-synchronize-to-dtk6.yml
=> feat: add workflow to sync dtk6

src/qml/FlowStyle.qml
fix the wrong highlight color in dark theme
Issue: https://github.com/linuxdeepin/developer-center/issues/6015
=> fix: Wrong highlight color in dark theme

misc/DtkDeclarativeConfig.cmake.in
=> fix: missing DeclarativePropertiesTarget

qt6/src/qml/TextField.qml, src/qml/TextField.qml
add context menu in TextField
Issue: https://github.com/linuxdeepin/developer-center/issues/6521
=> fix: There isn't context menu in TextField

linglong.yaml
modify dependency version in linglong.yaml
Log: Modify dependency version in linglong.yaml
=> chore: Modify dependecy version in linglong.yaml

linglong.yaml
change qmake to cmake in linglong.yaml
Log: Modify field value (kind) in linglong.yaml
=> chore: Modify field value (kind) in linglong.yaml

qt6/src/qml/FlowStyle.qml, src/qml/FlowStyle.qml
DSvgRender can't resolve some icon, e.g: `xlink:href="data:img/png;base64`
and we can find `png` firstly by modifing size to properly,
Issue: https://github.com/linuxdeepin/developer-center/issues/6291
=> refact: modify icon's size to 24

src/translations/dtkdeclarative.ts, src/translations/dtkdeclarative_zh_CN.ts
add translations for context menu
Issue: https://github.com/linuxdeepin/developer-center/issues/6712
=> fix: no translations for context menu

src/private/dblurimagenode.cpp, src/private/dquickbehindwindowblur.cpp
It refers to https://github.com/vioken/waylib/pull/268
=> feat: Optimize flags of RenderNode

qt6/src/qml/ComboBox.qml, src/qml/ComboBox.qml
Set autoExclusive explicitly.
Issue: https://github.com/linuxdeepin/developer-center/issues/6187
=> fix: Multi options selected for Combobox

qt6/src/qml/DialogWindow.qml, src/qml/DialogWindow.qml
This reverts commit f0a7d32a17ec7e1fdbcfeb6ccf340019fb0a60b2.
=> Revert "fix: failure passing implicit width"

qt6/src/qml/Menu.qml, src/qml/Menu.qml
=> chore: TypeError warning

CMakeLists.txt, debian/changelog
=> chore: update changelog to 5.6.23

src/private/dquickdciiconimage.cpp, src/private/dquickimageprovider.cpp
- fix: icon doesn't change when iconTheme changed
=> icon update

src/private/dquickiconimage.cpp
=> fix: build on qt5

qt6/src/qml/BoxPanel.qml, qt6/src/qml/ButtonBox.qml, qt6/src/qml/FlowStyle.qml, qt6/src/qml/InsideBoxBorder.qml, qt6/src/qml/ItemDelegate.qml, qt6/src/qml/ToolButton.qml, src/qml/BoxPanel.qml, src/qml/ButtonBox.qml, src/qml/FlowStyle.qml, src/qml/InsideBoxBorder.qml, src/qml/ItemDelegate.qml, src/qml/ToolButton.qml
=> fix: adjust style for launchpad used

debian/changelog
=> chore: update changelog to 5.6.24

qt6/src/qml/TextField.qml, src/qml/TextField.qml
add canPaste condition
Issue: https://github.com/linuxdeepin/developer-center/issues/7052
=> fix: can't disable paste

qt6/src/qml/FlowStyle.qml
normal property is not assigned.
=> fix: warning for insideBorderColor is invalid

src/private/dquickcontrolpalette.cpp
it appears when application is different with root window's
palette.
`qvariant_cast` gets application's palette, and `toQPalette`
gets root window's palette.
=> fix: incorrect palette in ColorSelector

src/dquickwindow.cpp, src/dquickwindow.h, src/private/dquickwindow_p.h
=> feat: support to specify theme type for window

qt6/src/qml/settings/NavigationTitle.qml, src/qml/settings/NavigationTitle.qml
Level 1 font size default (t6)
Issue: https://github.com/linuxdeepin/developer-center/issues/7086
=> chore: settings dialog navigation font size tweak

qt6/src/qml/FlowStyle.qml
70% ==> 60%
Issue: https://github.com/linuxdeepin/developer-center/issues/7784
=> chore: scrollbar hover color tweak

src/private/dquickkeylistener.cpp
=> fix: support qt 6.7

qt6/src/qml/FlowStyle.qml, src/qml/FlowStyle.qml
Adjust opacity for drop shadow.
=> fix: adjust style for HighlightPanel

examples/exhibition/main.qml
=> chore: change theme type for exhibition

docs/qml/noqml/dquickdciicon.zh_CN.dox, src/private/dquickdciiconimage.cpp, src/private/dquickdciiconimage_p.h
Export cache property of dciicon to user.
Log: export cache property to user
=> feat: export cache property to user

src/private/dquickbehindwindowblur_p_p.h
=> fix: not initialized for BehindWindowBlur

qt6/src/qml/FlowStyle.qml
normal: 50%->30%
hover: 60%->40%
Issue: https://github.com/linuxdeepin/developer-center/issues/8049
=> chore: Adjusting the transparency of the scrollbar

qt6/src/qml/FlowStyle.qml
=> chore: add margins for Popup with window's edges

qt6/src/qml/FloatingPanel.qml
=> feat: support to disable shadow for FloatingPanel

docs/qml/noqml/dqmlglobalobject.zh_CN.dox, docs/qml/noqml/dquickitemviewport.zh_CN.dox, qt6/src/qml/FloatingPanel.qml, qt6/src/shaders_ng/quickitemviewport-opaque.frag, qt6/src/shaders_ng/quickitemviewport.frag, src/dquickitemviewport.cpp, src/dquickitemviewport.h, src/private/dmaskeffectnode.cpp, src/private/dmaskeffectnode_p.h, src/private/dqmlglobalobject_p.h, src/private/dquickitemviewport_p.h, src/private/dsoftwareroundedimagenode.cpp, src/private/dsoftwareroundedimagenode_p.h
Fix InWindowBlur not effect if the backdrop content has alpha channel.
=> feat: add "compositionMode" property in ItemViewport

qt6/src/qml/CheckBox.qml, qt6/src/qml/RadioButton.qml, qt6/src/qml/Switch.qml, src/qml/CheckBox.qml, src/qml/RadioButton.qml, src/qml/Switch.qml
DciIcon's is not center in parent, and it's sourceSize is not
equal with width.
Issue: https://github.com/linuxdeepin/developer-center/issues/4177
=> fix: incorrect position for DciIcon

src/private/dquickitemviewport_p.h
MaskNode is required when radius equal zero or compositionMode is Source.
Issue: https://github.com/linuxdeepin/developer-center/issues/8668
=> fix: assert when radius is 0 in transparent window

qt6/src/qml/TextField.qml, src/qml/TextField.qml
Adding bounding check when show menu.
Issue: https://github.com/linuxdeepin/developer-center/issues/8472
=> fix: incomplete display for menu

qt6/src/qml/FocusBoxBorder.qml
Align the SearchEdit style with the QWidget style
Issue: https://github.com/linuxdeepin/developer-center/issues/8697
=> fix: modify the SearchEdit style

src/private/dquickimageprovider.cpp
use application-x-desktop instead of 10x10 black square
b4
now:
=> chore: invalid icon use application-x-desktop

qt6/src/qml/FlowStyle.qml, qt6/src/qml/Menu.qml, qt6/src/qml/MenuItem.qml
Adjusting UI
Issue: https://github.com/linuxdeepin/developer-center/issues/8631
=> fix: Menu is not blurry enough, and the arrow position is incorrect

qt6/src/qml/ArrowListView.qml, qt6/src/qml/Menu.qml, qt6/src/qml/MenuItem.qml
=> chore: add animation for menu

qmlplugin/qmlplugin_plugin.cpp, qt6/src/dquickextendregister_p.h, src/dquickwindow.cpp, src/dquickwindow.h, src/private/dquickwindow_p.h
add two interface setWindowEffect and setWindowStartUpEffect
Issue: https://github.com/linuxdeepin/developer-center/issues/10322
=> feat: support to change window effects

qt6/src/qml/FlowStyle.qml
adjust the handleGradientColor as required by the designer
Log:
=> chore: adjust the handleGradientColor

qt6/src/qml/FloatingMessage.qml
=> chore: modify message animation

qt6/src/qml/ButtonBox.qml, qt6/src/qml/FlowStyle.qml, qt6/src/qml/ToolButton.qml
- button text color opacity normal: 0.7(gray), hovered: 1.0(black)
- ButtonBox remove background
- toolbutton hover scale 1.2 ==> 1.1
- button radius: 8 ==> 6
=> chore: button style tweak

qt6/src/qml/FloatingPanel.qml
=> style: Add a necessary comment

qt6/src/qml/ComboBox.qml
ComboBox.qml:32:9: TypeError: Cannot read property 'width' of null
=> fix(ComboBox): Cannot read property 'width' of null

debian/changelog
release 5.0.35
Log: bump version to 5.0.35
=> chore: bump version to 5.0.35

src/dquickwindow.cpp
IsEnabled interface adapted to TreeLand platform
Log: Adapt to the Treeland platform
=> feat: Adapt to the Treeland platform

qt6/src/CMakeLists.txt, src/private/dbackdropnode.cpp, src/private/dmaskeffectnode.cpp, src/private/drectanglenode.cpp, src/private/drectanglenode_p.h
=> feat: Support Qt 6.8

src/private/dqmlglobalobject.cpp
reuired: https://github.com/linuxdeepin/dtkgui/pull/263
=> chore: testAttribute DGuiApplicationHelper::HasAnimations

qt6/src/CMakeLists.txt, src/private/dquickcontrolpalette.cpp
Update controlState when update control firstly.
=> fix: incorrect controlState when disable control

qt6/src/qml/TextField.qml
- only echoMode Normal enable `copy` and `cut`
- readonly disable `cut`
=> chore: edit contextMenu item enable tweak

qt6/src/qml/ArrowListView.qml
ArrowListView highlight was remove
partially revert https://github.com/linuxdeepin/dtkdeclarative/commit/af1277c91d0abb2fd50693700f0bf3287925d3dd
=> fix: combobox highlight missing

src/private/dquickcontrolpalette.cpp
=> chore: typo for QT_VERSION

qt6/src/qml/Label.qml
change opacity to 0.4 on disabled
=> fix: label text color not changed on enabled changed

qt6/src/qml/AboutDialog.qml, qt6/src/qml/BoxInsetShadow.qml, qt6/src/qml/BoxShadow.qml, qt6/src/qml/BusyIndicator.qml, qt6/src/qml/WaterProgressBar.qml
Use retainWhileLoading to prevent from clearing image cache.
=> fix: image cache cleared

src/private/dquickiconlabel.cpp
setRetainWhileLoading true for IconLabel
pms: Bug-293341
=> fix: itemdelegate icon flashed

qt6/src/qml/ArrowListView.qml, qt6/src/qml/ComboBox.qml, qt6/src/qml/Menu.qml
Using HighlightPanel to display highlight item.
pms: BUG-297003
=> fix: adjust UI for Menu and ComboBox

qt6/src/qml/ScrollBar.qml, src/dplatformthemeproxy.cpp, src/dplatformthemeproxy.h
=> feat: support to flow system settings for scrollBarPolicy

qt6/src/qml/BoxPanel.qml, qt6/src/qml/FlowStyle.qml, qt6/src/qml/HighlightPanel.qml, qt6/src/qml/private/ButtonPanel.qml
drop shadow and gradient color.
adjust Button's radius from6 to 8.
pms: BUG-297055
=> chore: drop shadow for BoxPanel

qt6/src/qml/Menu.qml
height isn't resize when set height.
pms:TASK-368399
=> fix: incorrect height for Menu when height is large

qt6/src/qml/ComboBox.qml, qt6/src/qml/FocusBoxBorder.qml, qt6/src/qml/Slider.qml, qt6/src/qml/Switch.qml
Add Switch,Slider,ComboBox focus style
pms: BUG-303539
=> fit: Add focus style

qt6/src/dquickextendregister_p.h
=> feat: export DSysInfo for QML

.tx/config, .tx/transifex.yaml, src/translations/dtkdeclarative_ar.ts, src/translations/dtkdeclarative_ast.ts, src/translations/dtkdeclarative_br.ts, src/translations/dtkdeclarative_cs.ts, src/translations/dtkdeclarative_da.ts, src/translations/dtkdeclarative_de.ts, src/translations/dtkdeclarative_fa.ts, src/translations/dtkdeclarative_fr.ts, src/translations/dtkdeclarative_gl_ES.ts, src/translations/dtkdeclarative_hi_IN.ts, src/translations/dtkdeclarative_hr.ts, src/translations/dtkdeclarative_it.ts, src/translations/dtkdeclarative_ko.ts, src/translations/dtkdeclarative_lt.ts, src/translations/dtkdeclarative_ms.ts, src/translations/dtkdeclarative_ne.ts, src/translations/dtkdeclarative_pt.ts, src/translations/dtkdeclarative_pt_BR.ts, src/translations/dtkdeclarative_ro.ts, src/translations/dtkdeclarative_ru.ts, src/translations/dtkdeclarative_sl.ts, src/translations/dtkdeclarative_sr.ts, src/translations/dtkdeclarative_tr.ts, src/translations/dtkdeclarative_zh_CN.ts
1. Updated Transifex configuration format in .tx/config
2. Added new transifex.yaml configuration file
3. Updated multiple translation files with new context and translations
4. Added AboutDialog translations for various languages
5. Fixed line number references in translation files
6. Improved existing translations in several languages
Log: Updated translation configurations and added new translations
Influence:
1. Verify all translations display correctly in the UI
2. Check AboutDialog translations in different languages
3. Test theme switching with updated translations
4. Verify settings dialog translations
5. Test application with different system languages
feat: 更新翻译配置和翻译内容
1. 更新了.tx/config中的Transifex配置格式
2. 新增了transifex.yaml配置文件
3. 更新了多个翻译文件，添加了新上下文和翻译
4. 为多种语言添加了AboutDialog的翻译
5. …
=> feat: update translation configurations and translations
