linuxdeepin/dtkdeclarative

src/dquickblitframebuffer.cpp, src/dquickwindow.cpp, src/private/dquickinwindowblur.cpp, src/private/dquickinwindowblur_p.h, src/private/dquickkeylistener.cpp, src/private/dquickwaterprogressattribute.cpp
1. Ambiguous classes with the same name under different files
2. Obsolete interfaces are wrapped with macro definitions
Log:
Issue: linuxdeepin/developer-center/issues#3316
Change-Id: I3a64b5a19adc8c749a88af4af6c98a5eabde25e4
=> fix: remove some build warnings

src/qml/WindowButtonGroup.qml
A trigger for the `active` property in the Loader was not added
to the partial use of WindowButton due to negligence, causing
the ColorSelector to update the control repeatedly, but because
it was not released, the ParentItem could not be obtained, resulting
in an inability to obtain the qml engine related resources and
causes a crash.
Log:
Change-Id: Ieb8a240044be4e73e8b0dac7dc18417518b951b9
=> fix: Crash caused by the WindowButton control

src/qml/ArrowListView.qml, src/qml/FlowStyle.qml, src/qml/Menu.qml, src/qml/private/ArrowListViewButton.qml
The implitHeight property should be independent of the height
property, the implitHeight only updates when the internal space
changes, the height property updates when the external space
changes.
Log:
Bug: https://pms.uniontech.com/bug-view-128715.html
Change-Id: Iee87d5e48b0ccdc58aaae53dff4ddd93abc53237
=> fix: menu height does not change with the window

src/private/dquickcontrolpalette_p.h, src/qml/FloatingPanel.qml, src/qml/FlowStyle.qml, src/qml/ToolTip.qml
1. The FloatingPanel control does not conform to the design, increasing
its inner and outer strokes and adapting to the bright and dark themes.
2. Reimplement the implementation of the tooltip control and delete the
old code.
3. Fix the problem that the default system theme in control palette is
not updated.
Log:
Change-Id: I880a2b73af3c5610cce4bbaab26bdd6a13867ad7
=> fix: Adjust the style of the FloatingPanel control

src/private/dmessagemanager.cpp, src/qml/ActionButton.qml, src/qml/SearchEdit.qml, src/qml/Slider.qml, src/qml/SliderTipItem.qml, src/qml/TextField.qml, src/qml/ThemeMenu.qml
1. Add the disable state for ActionButton, Switch and TextField controls
2. Remove the invalid default property in SearchEdit control.
3. Modify the inconsistency of dashOffset property in Slider control.
4. Adjust the spacing of SliderTipItem to ensure that the text and label
cannot be aligned in different states.
5. Modify the item spacing of the default container in MessageManager.
Log:
Change-Id: Ie13ef4cfd59c920b49f2e0cb8816c84f8d571697
=> fix: Adjust the abnormal problems in the control

examples/exhibition/Menu.qml, src/private/dquickcontrolpalette.cpp
change opacity when item disabled
Bug: https://pms.uniontech.com/bug-view-165235.html
Log: disabled item set opacity 0.4
Change-Id: I73ed6ba6003d4932557f79a16a4fb46975d21581
=> fix: disabled item text color not changed

src/qml/ArrowListView.qml, src/qml/Menu.qml
Add implicitWidth's binding to get max itemWidth as view's
width.
Add onWidthChanged to recalculate item's width for
checked Changed.
TODO: Binding loop detected for property "implicitWidth"，
and calculate item's width.
Log: 暂时解决菜单宽度的计算错误
Influence: 使用了菜单，并且菜单项比默认最小宽度还要大的应用
Change-Id: Ic0f67bc38980adb574f1a5347a718b9ef30b6942
=> fix: Modify Menu's width error

src/dquickwindow.cpp, src/private/dquickwindow_p.h
it's exist when application is startup automatically and wm's
flag fetch `_deepin_no_titlebar` info by error in platformplugin.
wm's flag is updated when recvs QXcbAtom::_NET_SUPPORTED, and
then emit hasNoTitlebarChanged signal.
related code is in dde-qt5platformplugins:
XcbNativeEventFilter::nativeEventFilter(QXcbAtom::_NET_SUPPORTED)
-> DXcbWmSupport::updateNetWMAtoms
-> DXcbWmSupport::updateHasNoTitlebar
Log: xcb延迟更新hasNoTitlebar，导致dtkdeclarative的Window.enabled错误
Bug: https://pms.uniontech.com/bug-view-168517.html
Influence: qml重构的授权客户端开机自启时，标题显示错误
Change-Id: I8481fae88a9effe29110647e84c43ebc0bec9558
=> fix: Window.enabled is invalid

src/qml/FloatingPanel.qml, src/qml/Menu.qml
Removing offScreen function.
TODO: 'offScreen' cause menu has rectangle background
in topLeft.
Log: 临时解决菜单首次弹出后需要移动鼠标才能显示的问题
Bug: https://pms.uniontech.com/bug-view-173409.html
Influence: 所有菜单应用，这会导致菜单左上角的圆角下存在直角背景
Change-Id: I353de34f50980303764f0967f2c8c14453a4151e
=> fix: Menu'popup can only work once

src/qml/DialogWindow.qml
Add Default handler to caclulate width and height when completed.
Add Control as Window's root item to bind palette.
Log: 对话框大小计算时机错误导致显示错误
Bug: https://pms.uniontech.com/bug-view-170365.html
Influence: 对话框首次显示错误
Change-Id: I7689f1bd23f576f1474df61760f3f67556df4a07
=> fix: DialogWindow's default size calculating error

src/private/dquickinwindowblur.cpp
Log: 切换主题对话框模糊出现
Bug: https://pms.uniontech.com/bug-view-169217.html
Influence: 所有对话框切换主题时颜色错误
Change-Id: I0870d8e68c716feffb6b7b0fc247155bb5070da8
=> fix: DialogWindow's palette Can't change flowing system

src/qml/ArrowListView.qml
Add fallback width for arrowListView.
Log: ArrowListView警告信息
Bug: https://pms.uniontech.com/bug-view-173393.html
Influence: 菜单不显示
Change-Id: Ic187a02987edf87b4ce279318683a9c3b596f6ec
=> fix: ArrowListView's ImplicitWidth error

examples/qml-app-template/src/main/CMakeLists.txt, examples/qml-app-template/src/main/main.cpp, examples/qml-app-template/src/maincomponentplugin/CMakeLists.txt, examples/qml-app-template/src/maincomponentplugin/maincomponentplugin.h, examples/qml-app-template/src/maincomponentplugin/plugin.json, examples/qml-app-template/src/preloadplugin/CMakeLists.txt, examples/qml-app-template/src/preloadplugin/plugin.json, examples/qml-app-template/src/preloadplugin/preloadplugin.h, src/dapploader.cpp, src/dapploader.h, src/private/dapploader_p.h, src/src.pro
using 'appid' filed to identify AppLoad's plugin instead of
plugin's name.
Modify DTK_QML_APP_PLUGIN_PATH's value in dtkdeclarative's
cmake and pri.
AppLoad find plugin's path is the order:
custom's addPluginPath ->
env: DTK_QML_PLUGIN_PATH ->
env: LD_LIBRARY_PATH/DTK_QML_APP_PLUGIN_SUBPATH ->
dtkdeclarative install path: DTK_QML_APP_PLUGIN_PATH,
We suggest user should set plugin's path using 'addPluginPath'.
Log: 修改插件的标识信息，安装路径，查找路径
Influence: 使用了AppLoader的qml应用若没适配可能崩溃
Change-Id: I24260967a814caa94000a63ee91bdbe223560c78
=> fix: Modify appload's plugin path

src/private/dblurimagenode.cpp
Add a check of null pointer, But it shouldn't have happened.
Log: 显示菜单偶发程序崩溃
Bug: https://pms.uniontech.com/zentao/bug-view-173435.html
Change-Id: I0100eb158f9ddf6909a931204dc6f3752614c78d
=> fix: null pointer cause crash

debian/control, examples/exhibition/CMakeLists.txt
Add as-need linker flags to fix lintian warning. Add ${misc:Depends} for doc package.
Log: fix lintian warnings.
=> chore: fix lintian warnings

misc/DtkDeclarativeConfig.cmake.in, src/CMakeLists.txt
Hide Qt5::DBus and Qt5::QuickPrivate that is used privately.
Log: hide private link libraries
=> chore: hide private link libraries

tests/CMakeLists.txt
PREFIX is not used so we remove it.
Log: remove useless macro define
=> chore: remove useless macro define

src/qml/WindowButton.qml
This commit doesn't change the effect, But I don't know why it
is ok.
App is crashed to access WindowButton's alias property of
"pressed" when WindowButton is unload, it means the different between `alias` and `property`.
We can reoccurrent this bug following these steps:
1. starting dtk-exhibition.
2. clicking bottom page in the left sidebar.
3. switch to anthor page quickly.
TODO: to locate the problem.
Log: none
Change-Id: I9c9bab1efaea7d94f73e09eda5e6963deef0cbb5
=> fix: Crash when WindowButton unload

docs/snippets/dtkdeclarative_boxinsetshadow.qml
Modify snippets's code to be compatible lower doxygen.
It's ok on 1.9.4 but wrong on 1.8.13.
Log: none
Change-Id: Ibcce8ce29b2f24f26e24268020768ef31292be57
=> chore: Build error in lower doxygen version

src/CMakeLists.txt
DTK_QML_APP_PLUGIN_PATH should be absolute. Add CMAKE_INSTALL_PREFIX.
Log: fix qml app plugin path error
=> fix: qml app plugin path error

src/private/dquickcontrolpalette.cpp, src/qml/BoxPanel.qml, src/qml/ButtonBox.qml
ColorSelector.hovered was disabled for all family.
There is a spectial animation as background change flowing hovered
for `CommonColor`.
=> Missing hover in crystalcolor

src/private/dquickiconlabel.cpp, src/private/dquickiconlabel_p_p.h, src/qml/AboutDialog.qml, src/qml/DialogWindow.qml
Fallback to IconLabel's size when unset icon's size.
Add palette property for Window.
Issue: https://github.com/linuxdeepin/dtkdeclarative/issues/123
=> fix: Abnormal display of IconLabel for dci icon

src/private/dblurimagenode.cpp
It was caused by 442d409ccbb0206dd577aab8351df4580e2bcc04.
It should to apply targetFBO whenever, and release it when
rendering completed.
It doesn't work when we show it firstly:
```
Item {
width: 400; height: 400
InWindowBlur {
id: blur
anchors.fill: parent
radius: 5
offscreen: true
ItemViewport {
anchors.fill: parent
fixed: true
sourceItem: parent
hideSource: false
radius: 5
}
Rectangle {
anchors.fill: parent
color: "green"
}
}
}
```
and it's ok if `offscreen` is set false.
Issue: https://github.com/linuxdeepin/dtkdeclarative/issues/121 https://github.com/linuxdeepin/dtk/issues/23
=> fix: InWindowBlur doesn't work correctly

src/private/dquickcontrolpalette.cpp
Add familyIndex when fetching Disabled color.
Issue: https://github.com/linuxdeepin/dtk/issues/43
=> fix: Missing family refator for ColorSelector

src/qml/DialogTitleBar.qml
Using Layout attach property instead of width itself.
Assign contentItem explicitly.
=> fix: Calculation error in DialogTitleBar's width

src/qml/RadioButton.qml
Assign palette.windowText to the color property.
Issue: https://github.com/linuxdeepin/dtk/issues/19
=> fix: RadioButton's text color error

examples/qml-inspect/Example_colorselector.qml, src/qml/FlowStyle.qml
It reports 'Invalid property assignment: unsupported type
"Dtk::Quick::DQuickControlColor"' in qt6.
because QQmlMetaType::registerCustomStringConverter has been dropped it maybe a bug for qt mentioned in
https://codereview.qt-project.org/c/qt/qtdeclarative/+/481153
=> fix: Unsupported type for property assignment

src/private/dqmlglobalobject.cpp, src/private/dqmlglobalobject_p.h, src/private/dqmlglobalobject_p_p.h
Using QQuickPalette instead of QPalette in Qt6, and it's function
is same as QPalette, so we only add a wrapper for QPalette.
=> feat: Support QQuickPalette in Qt6

chameleon/CMakeLists.txt
${QML_FILES} has been added qml.qrc, now we don't add it to
QML_FILES.
TODO: Changing plugin's generation.
=> fix: Report Network error in qt6

src/private/dqmlglobalobject_p.h
Related-commit: e00402256828d742054d946b369aadfed39da6a6
=> fix: Missing Macro for DColor in qt6

src/private/dblitframebuffernode.cpp, src/private/dblurimagenode.cpp, src/private/dmaskeffectnode.cpp
=> feat: Migrate qt5 to qt6 for QSGTexture

qt6/src/qml/TitleBar.qml
It maybe a bug for `qt5platform-plugins`.
TODO: fix in qt5platform-plugins.
=> fix: TitleBar can't drag in qt6

qt6/src/qml/AboutAction.qml, qt6/src/qml/TitleBar.qml, src/qml/AboutAction.qml, src/qml/TitleBar.qml
Don't need to assign aboutDialog property manually.
=> fix: Remove AboutAction's assignment

src/src.cmake
Override cmake variables, and it caused to uninstall some files.
=> fix: Missing files to install

CMakeLists.txt, chameleon/CMakeLists.txt, cmake/DtkBuildConfig.cmake, examples/exhibition/CMakeLists.txt, examples/qml-inspect/CMakeLists.txt, qmlplugin/CMakeLists.txt, qmlplugin/targets.cmake, qt6/src/CMakeLists.txt, qt6/src/qml/WindowButtonGroup.qml, qt6/src/qml/private/CMakeLists.txt, qt6/src/qml/settings/CMakeLists.txt, src/CMakeLists.txt, src/targets.cmake, tests/CMakeLists.txt, tests/main.cpp, tests/test-recoverage.sh, tests/ut_windowbuttongroup.cpp
Refactor the CMake code for better code reusability between qt5
and qt6.
the testing project is no longer compiled together with the
source code for code coverage, we add a option `ENABLE_COV`, and recompile the project.
Because the tests also load QML plugins that depend on libraries compiled from the source code, it leads to conflicts between the binary-loaded libraries and the original ones.
As a result, the registration information within QML is lost when loading QML plugins.
Add EventLoop for unit-test.
UT is wrong for WindowButtonGroup in qt6.
=> fix: Missing Qml registration info in test project

debian/control
It reports `module "QtGraphicalEffects" is not installed`
=> fix: Missing dependency for dtkdeclarative

tests/ut_dquickdciiconimage.cpp
crash when calling the interface isNull of DQuickDciIconImage
Log: fix the crash in ut_dquickdciiconimage
=> fix: crash in ut_dquickdciiconimage

tests/CMakeLists.txt, tests/apploaderplugindump/CMakeLists.txt, tests/apploaderplugindump/maincomponentplugin/CMakeLists.txt, tests/apploaderplugindump/maincomponentplugin/main.qml, tests/apploaderplugindump/maincomponentplugin/maincomponent.qrc, tests/apploaderplugindump/maincomponentplugin/maincomponentplugin.cpp, tests/apploaderplugindump/maincomponentplugin/maincomponentplugin.h, tests/apploaderplugindump/maincomponentplugin/plugin.json, tests/apploaderplugindump/preloadplugin/CMakeLists.txt, tests/apploaderplugindump/preloadplugin/Preload.qml, tests/apploaderplugindump/preloadplugin/plugin.json, tests/apploaderplugindump/preloadplugin/preload.qrc, tests/apploaderplugindump/preloadplugin/preloadplugin.cpp, tests/apploaderplugindump/preloadplugin/preloadplugin.h, tests/ut_dapploader.cpp
Add UT.
We add a simulator to test the plugin because we can't call
`AppLoader.exec`.
=> feat: Add UT for AppLoader-plugin

tests/test-recoverage.sh
those files don't need to add UT.
`dquickbusyindicator` isn't exported.
`dquicksystempalette` is depprecated.
=> chore: Remove some file for recoverage

src/private/dblitframebuffernode.cpp, tests/test_helper.hpp, tests/ut_dblitframebuffernode.cpp, tests/ut_dquickinwindowblur.cpp
QSGRenderNode::matrix() is invalid called in `render()`,
because QSGRenderNode is support in qt 6.2.
Skipping ut_quickinwindowblur and ut_dblitframebuffernode.
=> fix: UT failed in qt6

qt6/src/shaders_ng/shadowmaterial.frag, qt6/src/shaders_ng/shadowmaterial.vert, src/private/dshadownode_p.cpp
Layout of the QSGMaterialShader::uniformData() is wrong, because
the byte alignment in`glsl` and `cpp` are different.
=> fix: GlowEffect Invalid in qt6

src/private/dconfigwrapper.cpp, tests/ut_dconfigwrapper.cpp
It introduced in 7b58695d3745a30b91ff29367729ef6dc24f7086
We only use Wrapper's value as fallback value instead of current value. it is different between qt5 with qt6 for `property string key`, in qt5, it's value read in QMetaProperty is false for `isNull`, but it's true in qt6.
=> fix: Wrong DConfigWrapper's initialized value

src/private/dblurimagenode.cpp, src/private/dblurimagenode_p.h, src/private/dquickinwindowblur.cpp, tests/ut_dblurimagenode.cpp
It sames as the commit 4cf8a6b7ec3ca944d21e4c88831581adb38a0a00
We store window variable of the item to avoid invaild in some step, because render function is working in readerer thread and `window` of the item is in main thread, it maybe is nullptr in sometime, e.g: QQuickItem::setParentItem in QQuickPopup when switching visible.
We reserve the judgment of `m_item->window()` to reduce the possibility
of errors in render function.
TODO: QSGNode's render function shouldn't access QQuickItem.
Issue: https://github.com/linuxdeepin/developer-center/issues/5228
=> fix: crash at a nullptr QQuickWindow pointer

qt6/src/qml/settings/SettingsDialog.qml, src/qml/settings/SettingsDialog.qml
Using anchors to caculate width instead of assigning width
Issue: https://github.com/linuxdeepin/dtk/issues/44
=> fix: NavigationTitle is partially obscured

qt6/src/qml/PlaceholderText.qml, src/qml/PlaceholderText.qml
Set `elide` to fit to the Text item's width.
Issue: https://github.com/linuxdeepin/dtk/issues/42
=> fix: PlaceholderText out of range

src/private/dquickiconimage.cpp, src/private/dquickimageprovider.cpp
DciIcon's size is too large when app doesn't set AA_UseHighDpiPixmaps,
but pixmap will be blur when factor is greater than 1.0,
so app should set AA_UseHighDpiPixmaps.
Issue: https://github.com/linuxdeepin/developer-center/issues/6246
=> fix: DciIcon's size too long

archlinux/PKGBUILD, debian/control
don't build docs in arch and add dependency in debian.
=> fix: missing doxyqml

qt6/src/qml/CheckDelegate.qml, src/private/dquickdciiconimage.cpp, src/qml/CheckDelegate.qml
Fallback to QQuickIconImage when `name` is empty, it will try to
load icon by fallbackSource.
=> fix: DciIcon can't load icon by source

cmake/DtkBuildConfig.cmake, qt6/src/CMakeLists.txt, qt6/src/qml/settings/CMakeLists.txt
I don't know why RUNPATH is exist when linked ${LIB_NAME}.
so i skip it explicitly.
=> fix: insecure RUNPATH in arch

misc/DtkDeclarativeConfig.cmake.in, src/targets.cmake
It's wrong including way for DeclarativePropeties target .
=> fix: can't find so

qt6/src/qml/FlowStyle.qml
fix the wrong highlight color in dark theme
Issue: linuxdeepin/developer-center#6015
=> fix: Wrong highlight color in dark theme (Qt6)

qt6/src/qml/FlowStyle.qml, src/private/dmaskeffectnode.cpp, src/private/dmaskeffectnode_p.h, src/qml/FlowStyle.qml
Using platformTheme.windowRadius as Menu's radius,
it fallbacks to origin value when platformTheme invalid.
Adding nullptr check to avoid that app crashed when radius
is changed.
Issue: https://github.com/linuxdeepin/developer-center/issues/6380
=> fix: Menu's radius following system

qt6/src/qml/DialogWindow.qml, src/qml/DialogWindow.qml
We disable blur in qt6.
Modify width and height's Calculation method.
Issue: https://github.com/linuxdeepin/developer-center/issues/6654
=> fix: DialogWindow abnormal

src/dquickwindow.cpp, src/dquickwindow.h, src/private/dquickwindow_p.h
it reports `unique connections require a pointer to member
function of a QObject subclass` for UniqueConnection.
=> chore: warning for connect

src/private/dquickcontrolpalette.cpp
`updateChildrenPalettes` will emit QQuickPalette's changed signal
instead of QQuickItem's paletteChanged in qt6.
Issue: https://github.com/linuxdeepin/developer-center/issues/6724
=> fix: can't update palette when switching theme

qmlplugin/qmlplugin_plugin.cpp, qt6/src/CMakeLists.txt, qt6/src/dtkdeclarative_overridable_qml.qrc, qt6/src/qml/FloatingPanel.qml, qt6/src/qml/overridable/InWindowBlur.qml, src/private/dquickinwindowblur_p.h
Add a InWindowBlur to replace original InWindowBlurImpl.
external caller can intercept it by `QQmlAbstractUrlInterceptor`. e.g:
```
class DtkInterceptor : public QQmlAbstractUrlInterceptor
{
public:
QUrl intercept(const QUrl &path, DataType type)
{
if (path.path().endsWith("overridable/InWindowBlur.qml"))
return "MyBlur.qml";
return path;
}
};
```
=> feat: support to override for external caller

qt6/src/qml/Menu.qml, qt6/src/qml/Popup.qml, src/qml/Menu.qml, src/qml/Popup.qml
When window becomes inactive, there is no need to show popup. Add an option "closeOnInactive" to control if we should close popup when toplevel window becomes inactive. Default is true.
Log: close popup or menu on window deactivate
=> feat: close popup or menu on window deactivate

qt6/src/qml/DialogWindow.qml, src/qml/DialogWindow.qml
Cause DialogWindow use a layout with an item to layout children,
children's Layout properties is not directly passed to DialogWindow.
Use children rect's width to set preferredWidth.
Log: fix failure passing implicit width
=> fix: failure passing implicit width

src/private/dquickimageprovider_p.h
it causes shadowSize is wrong in release mode.
=> fix: missing initialization value for ShadowConfig

qt6/src/qml/MenuItem.qml, src/qml/MenuItem.qml
`highlighted` property is updated by Menu when handling key event.
=> fix: MenuItem can't be highlight by keyboard

src/private/dqmlglobalobject.cpp, src/private/dqmlglobalobject_p.h, src/private/dquickcontrolpalette.cpp
don't inverse color when the color type is Highlight or HighlightedText
Log: keep consistent highlight color in dark/light themes
=> chore: keep consistent highlight color in different themes

src/private/dqmlglobalobject.cpp
`data.color.type` is only valid when DColor is typed color,
and it also not be initialized.
=> fix: incorrect color type

src/private/dquickcontrolpalette.cpp
SearchEdit is not inherits QQuickControl, so it's ColorSelector
find it's parent as control, but SearchEdit's control status is
not equal with it's parent, it causes hover state is wrong.
=> fix: incorrect control for ColorSelector

docs/qml/noqml/dquickdciicon.zh_CN.dox, docs/qml/noqml/dquickiconimage.zh_CN.dox, src/private/dquickdciiconimage.cpp, src/private/dquickdciiconimage_p.h, src/private/dquickiconimage.cpp, src/private/dquickimageprovider.cpp
Use synchronous image providers for icon and dci icon, let user decide when to use asynchronous loading by setAsynchronous property in QtIcon and DciIcon. By default, the loading is asynchronous.
Log: export asynchronous property to user.
=> refact: export asynchronous property to user

src/private/dquickdciiconimage_p.h, src/private/dquickiconimage.cpp
* asynchornous --> asynchronous.
* set asynchronous to true in all constructors.
Log: fix typo and uninitialized asynchronous property
=> fix: typo and uninitialized asynchronous property

qt6/src/qml/FlowStyle.qml, qt6/src/qml/MenuItem.qml, src/qml/FlowStyle.qml, src/qml/MenuItem.qml
windowText color is highlight color when it's highlighted, and
ignore it's hover state.
=> fix: incorrect text color for MenuItem

qt6/src/qml/SearchEdit.qml, src/qml/SearchEdit.qml
log: centerIndicatorLabel color should follow control.placeholderTextColor
=> fix: can't set placeholder text color for SearchEdit

src/private/dquickcontrolpalette.cpp
- fix: incorrect control themetype for ColorSelector
Issue: https://github.com/linuxdeepin/developer-center/issues/7952
=> fix controltheme

docs/qml/noqml/dqmlglobalobject.zh_CN.dox, src/dquickwindow.cpp
When themeType is set, we should remove any binding in qml for property "palette". For example, ApplicationWindow will refresh palette when active changes.
Log: fix duplicate updates of palette
Issue: https://github.com/linuxdeepin/developer-center/issues/7826
=> fix: duplicate updates of palette

src/private/dquickdciiconimage.cpp
Disable align when centered.
Log: fix dci icon not centered
Issue: https://github.com/linuxdeepin/developer-center/issues/7941
=> fix: dci icon not centered

qt6/src/qml/SearchEdit.qml, src/qml/SearchEdit.qml
as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/8040
=> chore: incorrect font for SearchEdit's indicator text

src/private/dquickdciiconimage.cpp
Don't enable half align. Offset of image item is caused by layout,
when calculating width and height for image item, there is floating
point error compared with sourceSize, thus x and y is not zero.Set
width and height for image item to avoid calculation error of x and y.
Log: fix icon blurry when half aligned
=> fix: icon blurry when half aligned

src/dquickitemviewport.cpp
Don't assert, some source item's texture is null on initialing.
=> fix: crash at DQuickItemViewport::updatePaintNode

src/dquickwindow.cpp
=> fix: set shadowOffset when using DWindow

qt6/src/qml/SearchEdit.qml
Set icon source height explicitly.
Log: fix search icon not visible
Issue: https://github.com/linuxdeepin/developer-center/issues/8306
=> fix: search icon not visible

src/private/dquickitemviewport_p.h, src/private/dquickrectangle_p_p.h
mask's point maybe is extend if radius is float.
it causes mask's aplha is zero in top2bottom and right2left line.
Issue: https://github.com/linuxdeepin/developer-center/issues/8313
=> fix: mask area exist two line for viewport

src/private/dquickdciiconimage.cpp
Make dci icon has the same implicit size with internal image item. Thus anchors.centerIn will always put image item in the center of dci icon. Directly set implicit size of dci icon using the source size could cause a floating point error, which will cause a little bit offset of image item cause the two have different implicit size. In whole pixel alignment, image item will have a offset (1, 1).
Log: fix inconsistent implicit size in dci icon
=> fix: inconsistent implicit size in dci icon

src/private/dquickiconimage.cpp
Using QUrl to check FileUrl instead of string match.
=> fix: can't display local file for DciIcon

qt6/src/qml/FlowStyle.qml, qt6/src/qml/Menu.qml, qt6/src/qml/MenuItem.qml
TODO it exists some bug for InWindowBlur.
Issue: https://github.com/linuxdeepin/developer-center/issues/8631
=> refact: back to widget-like for Menu

qt6/src/qml/InsideBoxBorder.qml
The width of the insideboxborder does not change with screen scaling.
Issue: https://github.com/linuxdeepin/developer-center/issues/8530
=> fix: width of insideboxborder

qt6/src/qml/FloatingPanel.qml, qt6/src/qml/overridable/InWindowBlur.qml
The blur effect can be adjusted by blurMultiplier
Issue: https://github.com/linuxdeepin/developer-center/issues/9374
=> fix: added blurMultiplier adjustment

src/private/dquickiconimage.cpp
use Qt::SmoothTransformation when scale
Issue: https://github.com/linuxdeepin/developer-center/issues/8941
=> fix: DCiicon has aliasing when using base64 data

examples/exhibition/ControlGroup.qml, examples/exhibition/qml-qt6.qrc, qt6/src/dtkdeclarative_qml.qrc, qt6/src/qml.cmake, qt6/src/qml/ControlGroup.qml, qt6/src/qml/ControlGroupItem.qml
=> chore: add ControlGroup

qt6/src/qml/FloatingMessage.qml, src/private/dmessagemanager.cpp
add the animation for FloatingMessage
Log:
=> chore: add the animation for FloatingMessage

src/private/dquickdciiconimage.cpp
dciplayer has already set the devicePixelRatio, no need to divide by it here
=> fix: icon too small when devicePixelRatio > 1.0

qt6/src/qml/FloatingMessage.qml, src/private/dmessagemanager.cpp, src/private/dmessagemanager_p.h
add the closing animation for the message which can be closed automatically
Log:
=> chore: adjust the animation for FloatingMessage

qt6/src/qml/ControlGroup.qml
it's senseless that column layout fills the space available in ControlGroup,
so set Layout.fillHeight to false
Log:
=> fix: column layout fills the space available

qt6/src/qml/private/ProgressBarImpl.qml
add the animation for ProgressBar
Log:
=> chore: add the animation for ProgressBar

qt6/src/qml/ArrowListView.qml, qt6/src/qml/Menu.qml, qt6/src/qml/MenuItem.qml, src/private/dquickiconlabel.cpp, src/private/dquickiconlabel_p.h
add the enter transition animation
Log:
=> chore: adjust the animation for menu

qt6/src/qml/DialogTitleBar.qml, qt6/src/qml/DialogWindow.qml
change Control to Item, as Control do not let clicks and touches through to items below them.
Issue: https://github.com/linuxdeepin/dtk/issues/190
=> fix: can't move dialog window

qt6/src/qml/ButtonBox.qml, qt6/src/qml/DragItemsImage.qml, qt6/src/qml/ListView.qml, qt6/src/qml/private/ButtonPanel.qml
- hover background color tweak
- avoid warnning
- fix drag item image pixelated
=> Listview hover

qt6/src/qml/ControlGroup.qml
The size of dci icon becomes larger than before when updating the interface under the dpi > 1.0
Log:
=> fix: the display size of dci icon is exceptional

src/private/dquickdciiconimage.cpp
只在初始化和 sourceSizeChanged 时更新图标大小
防止出现 dpr > 1.0 时未设置 sourceSize 的 item 在 updatePlayer 时图标一直放大 没有设置 sourceSize 会根据图片大小去 match dci 中的图标大小
=> fix: icon size changed on paletteChanged

src/private/dbackdropnode.cpp, src/private/dquickbackdropblitter.cpp
- partially cherry-pick from waylib
- remove TextureChangedCallback when DQuickBackdropBlitter destroyed...
=> fix crashed on floatingmessage closed 

qt6/src/qml/ListView.qml, qt6/src/qml/Switch.qml
- switch animation duration 500ms
- listview hovered background color remove shadowcolor
- listview hovered background size adapt to hovered item's background
=> chore: animation tweak

qt6/src/qml/FlowStyle.qml, qt6/src/qml/Menu.qml
=> chore: tweak the menu animation

qt6/src/qml/BoxPanel.qml, qt6/src/qml/ListView.qml
- enableBoxShadow: false
- dropShadowColor: null
=> chore: listview hover background color tweak

qt6/src/qml/FloatingPanel.qml, src/private/dquickitemviewport_p.h
When the background is transparent, the first time using ItemViewport to crop rounded corners, anti aliasing is already present, and the second time no longer requires anti aliasing
Issue: https://pms.uniontech.com/bug-view-271399.html
=> fix: Incorrect corner cutting of FloatingPanel

qt6/src/qml/ComboBox.qml, src/qml/ComboBox.qml
=> fix: Combobox shadow is cliped

src/private/dbackdropnode_p.h, src/private/dquickbackdropblitter.cpp
updatePaintNode will be executed  multiple times, so it should at least
be a slot function that only connects once, and `node` maybe
a invalid pointer, because QSGNode and QuickItem are managed by
two different threads.
We can use `m_item` to adjust whether the texture is valid, because
it's a QPointer for QQuickItem.
=> fix: app crashed when when InWindowBlur switching frequently

qt6/src/qml/ToolTip.qml, src/qml/ToolTip.qml
Bug: https://pms.uniontech.com/bug-view-271423.html
Log: Use normal wrap mode instead of WordWrap for ToolTip.Text
=> feat: Use normal wrap mode instead of WordWrap for ToolTip.Text

src/private/dquickimageprovider.cpp
The default icon needs to be scaled when the system scales.
Log: the default icon is displayed incorrectly
Bug: https://pms.uniontech.com/bug-view-277471.html
=> fix: the default icon is displayed incorrectly when zooming

src/CMakeLists.txt, src/dtkdeclarative_assets.qrc, src/dtkdeclarative_shaders.qrc
dtkdeclarative_asserts is required on qt5 and qt6, but
shaders is separate.
=> fix: shaders conflicting in qt6

src/dtkdeclarative_assets.qrc
add switch button icon to qrc file
Bug: https://pms.uniontech.com/bug-view-276703.html 
Log:
=> fix: switch button's icon is not found

qt6/src/qml/TextField.qml
=> fix: placeholder text horizontalAlignment not work

qt6/src/qml/ButtonBox.qml, qt6/src/qml/ItemDelegate.qml, qt6/src/qml/ListView.qml, qt6/src/qml/Switch.qml, qt6/src/qml/ToolButton.qml, src/private/dqmlglobalobject.cpp, src/private/dqmlglobalobject_p.h, src/private/dquickdciiconimage.cpp
add `DTK.hasAnimation` property  and `DQMLGlobalObject::hasAnimation()`
=> Switch animations

qt6/src/qml/ControlGroup.qml, qt6/src/qml/ControlGroupItem.qml, qt6/src/qml/FloatingMessage.qml, qt6/src/qml/Menu.qml
add the switch for animtions about menu, Notification, progressbar
Log:
=> chore: add the switch for animations

src/private/dbackdropnode.cpp
ProxyRenderTarget's size doesn't update.
Bug: https://pms.uniontech.com/bug-view-269551.html
=> fix: incorrect render area for InWindowBlur when resizing window

src/private/dquickbehindwindowblur.cpp
如果StyledBehindWindowBlur位于Loader中，则在Loader变为非活动状态时，可能触发DQuickBehindWindowBlur渲染任务中引用已释放的对象导致程序崩溃。通过使用QPointer修复了这个问题：在m_item为非法时放弃渲染。
Log:
=> fix: StyledBehindWindowBlur crash in render thread

qt6/src/qml/FlowStyle.qml, qt6/src/qml/Menu.qml
Bug:
https://pms.uniontech.com/bug-view-276581.html
https://pms.uniontech.com/bug-view-279723.html
Log: Adjust menu styles
=> fix: Adjust menu styles

src/private/dquickcontrolpalette.cpp
do not set value if control's window is null
Issue: https://github.com/linuxdeepin/dtk/issues/193
=> fix: crashed on palette destroyed

src/dquickwindow.cpp, src/private/dquickcontrolpalette.cpp
Delay to create appLoaderItem, and it's lifecycle is managed by parentItem.
DPalette of QQmlOpenMetaObjectType  isn't release.
Log: as title.
pms: Task-368399
=> fix: memory leak

qt6/src/qml/ComboBox.qml
如果model来自C++的QVarientList，则只能通过modelData[control.textRole]去访问数据
pms: TASK-368711
=> fix: combobox does not display content

qmlplugin/qmlplugin_plugin.cpp, qt6/src/qml/BoxShadow.qml, src/private/dquickborderimage.cpp, src/private/dquickborderimage_p.h, src/qml/BoxShadow.qml
=> fix: Boxshadow displays abnormally in fractional scaling scenarios

chameleon/CMakeLists.txt
qt_add_qml_module VERSION 不支持 4 位版本号
=> chore: build version support

src/private/dquickdciiconimage.cpp, src/private/dquickdciiconimage_p.h
=> feat: export retainWhileLoading for DciIcon

qmlplugin/qmlplugin_plugin.cpp, src/private/dquickborderimage_p.h, src/qml/BoxShadow.qml, src/src.cmake
Drop DQuickBorderImage in qt5.
pms: BUG-291539
=> fix: missing QQuickBorderImage symbol fo BoxShadow  in qt5

src/private/dquickcontrolpalette.cpp
Remove cached in qt6.8.
pms: BUG-289241
=> fix: ColorSelector can't read builtin property firstly in qt6.8

src/dquickwindow.cpp
When the specified area is blurred, fallback to global blur is not supported
pms: TASK-368711
=> fix: StyledBehindWindowBlur blur failure

qt6/src/qml/CheckDelegate.qml, qt6/src/qml/ItemDelegate.qml
hovered background missing when Dtk.hasAnimation false
pms: Bug-293075
=> fix: ItemDelegate/Checkdelegate hover background missing

qt6/src/qml/ComboBox.qml
If flat is true, it defaults to right alignment
Log:
=> feat: Export the alignment property of Combobox

qt6/src/qml/EditPanel.qml
Do not display AlertToolTip when alertText is empty
Log:
pms: BUG-287159
=> fix: Do not display AlertToolTip when alertText is empty

src/private/dquickiconimage.cpp
qApp.devicePixelRatio != window.effectiveDevicePixelRatio in treeland
=> fix: icon size not update on dpr changed

qt6/src/qml/ArrowListView.qml, qt6/src/qml/LineEdit.qml, src/qml/ArrowListView.qml, src/qml/LineEdit.qml
- fix arrow button and item text overlap 
- lineedit  right padding 0 ==> 10 without clear button
修改前 
修改后
=> arrowlistview not clip  &&  lineedit rightpadding to small 

src/private/dquickcontrolpalette.cpp
qApp maybe is nullptr, so we check QCoreApplication::closingDown
before call QObjectPrivate::get(qApp).
pms: TASK-368399
=> fix: access nullptr when app exited

qt6/src/qml/FlowStyle.qml, qt6/src/qml/HighlightPanel.qml, qt6/src/qml/Menu.qml, qt6/src/qml/MenuItem.qml
It's consistent with QMenu.
Fallback padding from 0 to 6.
Fallback subMenu's background.
pms: BUG-297003
=> fix: adjust UI for MenuItem

qt6/src/dquickextendregister_p.h, src/private/dqmlglobalobject_p.h
Removing warning.
pms: TASK-368399
=> fix: incorrect registering way for qt6

qt6/src/qml/ArrowListView.qml, qt6/src/qml/ComboBox.qml, qt6/src/qml/Menu.qml
Adjust Item's width for ComboBox.
Remove ArrowListView's highlight.
pms: BUG-297137
=> fix: incorrect Highlight for Menu

qt6/src/qml/Menu.qml
The bug can be see at QTBUG-99897.
pms: BUG-300051
=> fix: Menu's focus not be clean

qt6/src/qml/WindowButtonGroup.qml, src/dquickwindow.cpp, src/dquickwindow.h
It maybe the difference between qml and qwidget.
We can use xwininfo to get _NET_WM_STATE, Window's state is
missing MAXIMIZED state when clicked minimize button for qml app,
but it's exist in qwidget's app.
We refer to qwidget to implement it.
pms:BUG-281185
=> fix: MinimizeButton behavior mismatch with qwidget

qt6/src/qml/Menu.qml
Using implicitWidth instead of width of ColumnLayout, and
filling it's parent for ColumnLayout.
pms: BUG-303357 BUG-302791
=> fix: incorrect width for Menu

src/private/dconfigwrapper.cpp, src/private/dconfigwrapper_p.h, src/private/dsettingscontainer.cpp, src/private/dsettingscontainer_p.h, tests/qml/Config.qml, tests/ut_dconfigwrapper.cpp
The DConfig is a sync IO API, call it's API maybe block the GUI thread on the DConfigWrapper, so we need use the DConfig in a new thread.
=> feat: using DConfig in the non-GUI thread
